login-- MySQL Workbench Synchronization
-- Generated: 2020-11-20 11:03
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Dell

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `CPF` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `Senha` VARCHAR(150) NULL DEFAULT NULL,
  `Cel` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `mydb`.`cadastro` (
  `idcadastro` INT(11) NOT NULL AUTO_INCREMENT,
  `CPF` INT(11) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  `RG` INT(11) NULL DEFAULT NULL,
  `Data_nasc` DATETIME NULL DEFAULT NULL,
  `CEP` INT(11) NULL DEFAULT NULL,
  `Rua` VARCHAR(200) NULL DEFAULT NULL,
  `Bairro` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  `n_res` INT(11) NULL DEFAULT NULL,
  `Sexo` VARCHAR(2) NULL DEFAULT NULL,
  `Renda` INT(11) NULL DEFAULT NULL,
  `Profissao` VARCHAR(45) NULL DEFAULT NULL,
  `Tel_prof` INT(11) NULL DEFAULT NULL,
  `Tel_res` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idcadastro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
